apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-example-apps
  annotations:
    github.com/project-slug: dev-tooling-alg/argocd-example-apps
    argocd/app-name: guestbook
    backstage.io/kubernetes-id: guestbook-ui
    backstage.io/kubernetes-namespace: default
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
